version: '2'
services:
  nginx:
    build: ./build-context/
    ipc: host
    environment:
       - FROM_SHELL_RUN_ENVIRONMENT_IS_DEV=${FROM_SHELL_RUN_ENVIRONMENT_IS_DEV} # FAQ? https://www.savantcare.com/internal-discourse/t/2254
    volumes:
       - ./scripts:/var/www/html/phq9
       - /gt/sc-prog-repos/v1-app-phq9/nginx.conf:/etc/nginx/nginx.conf
    networks:
       - emr
    logging:
      driver: 'syslog'
      options:
         syslog-address: 'tcp://clcentrallogcollectionserver_server_1:514'
         mode: 'non-blocking'
  
networks:
  emr:
    external:
      name: emr_default
